   - name: Build & package IPA
     script: |
       cd elder_life
       flutter clean
       flutter pub get
       flutter build ipa --release --no-codesign

       # Create Payload folder and copy the .app into it
       mkdir -p build/ios/ipa/Payload
       cp -R build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app build/ios/ipa/Payload/

       # Zip into an unsigned IPA
       cd build/ios/ipa
       zip -q -r Runner.ipa Payload
       ls -la

