workflows:
  ios_build:
    name: iOS Build
    environment:
      flutter: stable
    scripts:
      - name: Build & package IPA
        script: |
          cd elder_life
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -q -r Runner.ipa Payload
          ls -la
    artifacts:
      - elder_life/build/ios/ipa/Runner.ipa
