name: elder_life
description: "Commander Life Tracking App for Magic: The Gathering"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  cached_network_image: ^3.4.1  # 
  provider: 6.1.4  # 
  flutter_hooks: ^0.21.2
  http: ^1.3.0
  font_awesome_flutter: ^10.0.0
  flutter_svg: ^2.1.0  # 
  path_provider: ^2.0.14
  share_plus: 10.1.4
  qr_flutter: ^4.0.0

  google_sign_in: ^5.4.0
 
  firebase_database: ^11.3.5  # 
  firebase_core: ^3.13.0  # Updated version of firebase_core
  firebase_auth: ^5.5.2   # Updated version of firebase_auth
  fluttertoast: ^8.2.12    # Keep the fluttertoast version
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # 
  flutter_launcher_icons: ^0.14.3  # 

flutter:
  uses-material-design: true

  assets:
    - assets/background.jpg
    - assets/Offline_Game_Icon.PNG
    - assets/Online_Game_Icon.PNG
    - assets/Player_Icon.PNG
    - assets/Profile_Icon.png
    - assets/players_bg.png
    - assets/player_detail_bg.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
