name: elder_life
description: "Commander Life Tracking App for Magic: The Gathering"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  uuid: ^4.5.1
  cached_network_image: ^3.3.0  # For caching commander images
  provider: 6.1.2  # If you're using Provider for state management
  flutter_hooks: ^0.21.2  # Optional for reactive state management
  http: ^1.3.0
  font_awesome_flutter: ^10.0.0
  flutter_svg: ^2.0.0
  path_provider: ^2.0.11
  share_plus: 10.1.4
 

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/background.jpg
    - assets/Offline_Game_Icon.PNG
    - assets/Online_Game_Icon.PNG
    - assets/Player_Icon.PNG
    - assets/Profile_Icon.png
    - assets/players_bg.png
    - assets/player_detail_bg.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


